### ISSUE TITLE
X11 phyloselect.R

### ISSUE THREAD

**Issue by T-B-F** [itsmeludo/PhylOligo#2]
If phyloselect.R is used remotely, ex. through ssh without X forwarding, the script crash with the error message:
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
  unable to start device X11cairo
Calls: X11
In addition: Warning message:
In X11(width = 12, height = 10) :
  unable to open connection to X11 display ''
Execution halted

I guess the culprit is this line:
X11(width=12,height=10) # external display when script is launched with Rscript command

Could it be passed as an option and if not set dump the plots in a folder?

**Comment by itsmeludo** [comment]
in  short, no. :/
X11 is needed by the function from ape to dynamically select a clade on the plot with the mouse. X11 is a dependency then. I will add it to the list and will add a description if Phyloselect need to be run remotely over ssh.
