### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by johrollin** [itsmeludo/PhylOligo#5]
Hi,

During the install I had the following error:

cmd: python3 setup.py install --home=/PhylOligo-1.0

'error: file '/src/contalocate.R' does not exist'

All the other files are correctly find and copy in the build folder. I guessed the problem come from the path write in setup.py. 
So I replace '/src/contalocate.R' by 'src/contalocate.R' line 29 it works !

You may want to do the change in you master.

J.Rollin
LABGeM/Génoscope team

**Comment by itsmeludo** [comment]
Merci!

2017-07-10 17:23 GMT+02:00 johrollin <notifications@github.com>:
