### ISSUE TITLE
error while loading shared libraries: libimf.so: cannot open shared object file: No suc h file or directory

### ISSUE THREAD

**Issue by U201412486** [itsmeludo/PhylOligo#6]
Hi,
I have a question and need your help.
I ran the program like this below.
  **
phyloligo.py -c 8 -i $assembly -k 4 -d JSD --method joblib -o
 JSD_4.mat
**
 It produced the report like this below.
**
infoseq: error while loading shared libraries: libimf.so: cannot open shared object file: No suc
h file or directory
Error in system(paste("infoseq -auto -nocolumns -only -noheading -length ",  : 
  error in running command
Execution halted
**
Any advice? Looking forwarding to your reply.

**Comment by itsmeludo** [comment]
Hi,
 Thanks for your message,
It seems that emboss has to be tested in the command line shell and maybe reinstalled. that would be my first guess.

The libimf seems not linked to phyloligo but rather a linux mishap, try addind he right path to LD_LIBRARY_PATH, according to your distribution: https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/268431

May i ask you which operating system and version you are using?

Best,

**Comment by U201412486** [comment]
Hi,
I am using CentOS release 6.6.And I had the LD_LIBRARY_PATH environment variable set to include the correct compiler library according to your advice,it did not work.And It reported the same error.
**
export PATH=/public/software/compiler/intel/composer_xe_2013_sp1.0.080/compiler/lib/intel64/lib
imf.so:$PATH
**
Any advice?

**Comment by itsmeludo** [comment]
Hi,
 Thanks for your message,
It seems that emboss has to be reinstalled, that would be my first guess.
