### ISSUE TITLE
Plot from phyloselect.py

### ISSUE THREAD

**Issue by alexcorm** [itsmeludo/PhylOligo#7]
Hi,

I would like to know if it's possible to add a legend to the plot? It would be great to have the link between the color and the cluster file.

And instead of having a png file, could we have a pdf file?

Thanks!

**Comment by T-B-F** [comment]
Hi,
I modified the plot_labels function which should now add a legend to the plot (634279b).
Png files are currently more convenient for us but you could easily convert them using external tools.
