### ISSUE TITLE
Legacy install: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5114: ordinal not in range(128)

### ISSUE THREAD

**Issue by ckeeling** [itsmeludo/PhylOligo#9]
Hello, I am using your "legacy install" method to create an ubuntu Singularity recipe, but I am getting the following error at the last command: 
```
apt-get update
apt-get install -y python3-dev python3-setuptools r-base git emboss samtools
apt-get install -y git python3-pip

git clone https://github.com/itsmeludo/PhylOligo.git
cd PhylOligo
pip3 install .
```

```Processing /PhylOligo
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-w9674ajh-build/setup.py", line 21, in <module>
        long_description=readme(),
      File "/tmp/pip-w9674ajh-build/setup.py", line 9, in readme
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5114: ordinal not in range(128)
    
```

Any suggestions how to resolve this?

**Comment by itsmeludo** [comment]
Hi,
 Thanks for the feedback. I changed the file a little I think and probably included some non ASCII characters(s) with a bad typing shortcut or so. I'll look into this tomorrow.

**Comment by itsmeludo** [comment]
I couldn't reproduce the error, could you tell me more about your setup?
I changed some tabulations to spaces and the end of the file, but I do not see a non ascii character at the end of it.

the problem is still there on the commit [6a86249](https://github.com/itsmeludo/PhylOligo/commit/6a862490c6d9776271f7c18f47c3ba195dcb3992)?

**Comment by ckeeling** [comment]
I have a very simple set up. I pull the Docker ubuntu image from here: https://hub.docker.com/_/ubuntu
and then install as per the code above for a legacy install. I'm afraid I still get the same error after the above commit.

**Comment by ckeeling** [comment]
Should the README.md be only in ascii? Is it possible that it is the README.md that is the problem?  I.e. are there non-ascii characters in this?  Line 9 in readme has the back-ticks; if I remove them (with ```sed -i 's/\`\`\`//g' README.md```) it doesn't solve the problem, but the error message changes slightly (position):
```Processing /PhylOligo
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-lb_quess-build/setup.py", line 21, in <module>
        long_description=readme(),
      File "/tmp/pip-lb_quess-build/setup.py", line 9, in readme
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5084: ordinal not in range(128)
```

**Comment by ckeeling** [comment]
Found it, it is the accented e in Ménigaud of the README.md (Lines 131 and 195). Fixed by:
```sed -i 's/Ménigaud/Menigaud/g' README.md```
The first instance is at the 5115th character in README.md.

**Comment by itsmeludo** [comment]
Thanks for the solution!
This accent has been up for quite some time, I'm very surprised this error only rise now. The readme is a UTF-8 file, so accent should be ok. Which encoding or locale are you using?

**Comment by ckeeling** [comment]
I have now included the following but I still get the same error:

```
apt-get install -y language-pack-en-base locales
locale-gen en_US.UTF-8
dpkg-reconfigure locales
```

It is probably an issue with my set up rather than this file, so I will close this issue.  I need to understand locales better.  Cheers,
